<?php
/**
 * Copyright (c) 2023 by https://github.com/annysmolyan
 *
 * This module provides video call functionality for an e-commerce store.
 * For license details, please view the GNU General Public License v3 (GPL 3.0)
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var ManagerTopLinksViewModel $viewModel
 */

use BelSmol\VideoCall\ViewModel\ManagerTopLinksViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$viewModel = $block->getViewModel();
?>

<ul class="header links">
    <li class="greet welcome">
        <span class="logged-in"><?= $escaper->escapeHtml($viewModel->getWelcomeMessage()); ?></span>
    </li>
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <button type="button" class="action switch" tabindex="-1" data-action="customer-menu-toggle">
                <span>Change</span>
            </button>
        </span>
        <div class="customer-menu" data-target="dropdown">
            <ul class="header links">
                <li class="link authorization-link" data-label="or">
                    <a href="<?=  /* @escapeNotVerified */ $viewModel->getLogoutUrl(); ?>"><?= __("Sign Out"); ?></a>
                </li>
            </ul>
        </div>
    </li>
</ul>
