<?php
/**
 * Copyright (c) 2023 by https://github.com/annysmolyan
 *
 * This module provides video call functionality for an e-commerce store.
 * For license details, please view the GNU General Public License v3 (GPL 3.0)
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * @var Template $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>

<h3><?= $escaper->escapeHtml(__("Active Call Queue")); ?></h3>

<div id="managerCallList" data-bind="scope:'managerCallList'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#managerCallList": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "managerCallList": {
                        "component": "BelSmol_VideoCall/js/components/managerCallList"
                    }
                }
            }
        }
    }
    </script>
</div>
